---
- hosts: nodes
  remote_user: root
  tasks:
  - name: Create textfile_collector directory
    file:
      path:    /var/lib/node_exporter/textfile_collector
      state:   directory
      owner:   root
      group:   root
      mode:    0775
  - name: Copy dockerinfo to node
    copy:
      src:   dockerinfo.sh
      dest:  /usr/local/bin/dockerinfo.sh
      owner: root
      group: root
      mode:  0755
  - name: Copy cron.d/docker_info.cron to node
    copy:
      src:   dockerinfo.cron
      dest:  /etc/cron.d/dockerinfo.cron
      owner: root
      group: root
      mode:  0644
  - name: Restart crond service on node
    systemd:
      name: crond
      state: restarted
