---
# Get latest Node Exporter software
- hosts: localhost
  tasks:
  - name: Download latest node_exporter binary
    get_url:
      url: https://github.com/prometheus/node_exporter/releases/download/v0.15.0/node_exporter-0.15.0.linux-amd64.tar.gz
      dest: /tmp/node_exporter.tgz
  - name: Untar node_exporter binary
    unarchive:
      src: /tmp/node_exporter.tgz
      dest: /tmp
      copy: no

# Now set up all nodes running OpenShift software with the Node Exporter
- hosts: nodes
  remote_user: root
  tasks:
  - name: Copy node-exporter binary to node
    copy:
      src:   /tmp/node_exporter-0.15.0.linux-amd64/node_exporter
      dest:  /usr/local/bin/node_exporter
      owner: root
      group: root
      mode:  0755
  - name: Set up Service for node-exporter
    copy:
      src:   node_exporter.conf
      dest:  /etc/systemd/system/node_exporter.service
      owner: root
      group: root
      mode:  0644
  - name: Start node_exporter service on node
    systemd:
      name: node_exporter
      enabled: yes
      state: started
      daemon_reload: yes
  # Open Firewall Port 9100 for future sessions by adding the rule to
  # the iptables file.
  - name: Open Firewall port 9100 for future sessions
      lineinfile:
        dest: /etc/sysconfig/iptables
        insertafter: '-A FORWARD -j REJECT --reject-with icmp-host-prohibited'
        line: '-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 9100 -j ACCEPT'
        state: present
  # Open Firewall Port 9100 for current session by adding the rule to the
  # current iptables configuration. We won't need to restart the iptables
  # service - which will ensure all OpenShift rules stay in place.- name: Restart IP Tables service
  - name: Open Firewall Port 9100 for current session
    iptables:
      action: insert
      protocol: tcp
      destination_port: 9100
      state: present
      chain: OS_FIREWALL_ALLOW
      jump: ACCEPT

# Clean up on Localhost
# Delete the downloaded and unarchived files
- hosts: localhost
  tasks:
  - name: Cleanup localhost /tmp
    file:
      path: /tmp/node_exporter.tgz
      state: absent
  - name: Cleanup localhost unarchived directory
    file:
      path: /tmp/node_exporter-0.15.0.linux-amd64
      state: absent
